### PR TITLE
Add completion for ZSH ( reference #57).

### PR DESCRIPTION
**Pull request by osaris**

### CODE REVIEW

**Comment by bunnymatic** [comment]
We'll roll this out with the next push.  Thanks for the updates.

**Comment by Zhomart** [comment]
It didn't work for me without argument "-U" for autoload.

```zsh
autoload -U bashcompinit
bashcompinit
source $(dirname $0)/lunchy-completion.bash
```

zsh version
```
zsh 5.0.5 (x86_64-apple-darwin14.0)
```

**Comment by osaris** [comment]
@Zhomart i'm running the same version. What means the ```-U``` operator ?

**Comment by Zhomart** [comment]
@osaris I don't know what `-U` means. Zsh's doc is on sourceforge, which is currently under maintenance. I found it here http://star.mit.edu/cluster/docs/0.92rc2/manual/shell_completion.html

**Comment by akatrevorjay** [comment]
A bit late, but: `-U` means to only load it if it doesn't already exist. It can also be used to dedupe arrays.

**Pull request merged**
